// This file was generated by an automated script based on a user request.
// It represents an Angular service for fetching data via HTTP.

import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';

// Define an interface for the expected data structure (optional but recommended)
export interface DataItem {
  id: number;
  name: string;
  // Add other properties as needed
}

@Injectable({
  providedIn: 'root' // Makes the service a singleton, available application-wide
})
export class DataFetchService {

  // Define the base URL for your API
  private apiUrl = 'https://api.example.com/data'; // Replace with your actual API URL

  constructor(private http: HttpClient) { }

  /**
   * Fetches data from the API endpoint.
   * @returns An Observable containing an array of DataItem objects.
   */
  fetchData(): Observable<DataItem[]> {
    // The HttpClient.get method returns an Observable
    // Type the response using the <DataItem[]> generic
    return this.http.get<DataItem[]>(this.apiUrl);
  }

  /**
   * Fetches a single data item by its ID.
   * @param id The ID of the item to fetch.
   * @returns An Observable containing a single DataItem object.
   */
   fetchDataById(id: number): Observable<DataItem> {
    const url = `${this.apiUrl}/${id}`;
    return this.http.get<DataItem>(url);
  }

  /**
   * Posts data to the API endpoint.
   * @param data The data object to send.
   * @returns An Observable containing the response from the server.
   */
   postData(data: any): Observable<any> {
    // The HttpClient.post method returns an Observable
    return this.http.post(this.apiUrl, data);
  }
}